version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
    version_requirement_updates: "increase_versions"